/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDto } from '../../models/task-dto';

export interface GetUserTasks$Params {
  userId: number;
}

export function getUserTasks(http: HttpClient, rootUrl: string, params: GetUserTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskDto>>> {
  const rb = new RequestBuilder(rootUrl, getUserTasks.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskDto>>;
    })
  );
}

getUserTasks.PATH = '/api/projects/{projectId}/tasks/user/{userId}';
