/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentDto {
  content?: string;
  created?: string;
  id?: number;
  taskId?: number;
  updated?: string;
  userId?: number;
}
