/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectDto {
  description?: string;
  endDate?: string;
  id?: number;
  name?: string;
  startDate?: string;
}
