/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskDto {
  completed?: boolean;
  description?: string;
  endDate?: string;
  id?: number;
  name?: string;
  projectId?: number;
  userId?: number;
}
