/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  email?: string;
  id?: number;
  password?: string;
  role?: 'ROLE_ADMIN' | 'ROLE_USER';
  username?: string;
}
