/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TeamDto } from '../../models/team-dto';

export interface AddTeamUser$Params {
  teamId: number;
  userId: number;
}

export function addTeamUser(http: HttpClient, rootUrl: string, params: AddTeamUser$Params, context?: HttpContext): Observable<StrictHttpResponse<TeamDto>> {
  const rb = new RequestBuilder(rootUrl, addTeamUser.PATH, 'post');
  if (params) {
    rb.path('teamId', params.teamId, {});
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TeamDto>;
    })
  );
}

addTeamUser.PATH = '/api/teams/{teamId}/users/{userId}';
