/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TeamDto } from '../../models/team-dto';

export interface CreateTeam$Params {
  projectId: number;
      body: TeamDto
}

export function createTeam(http: HttpClient, rootUrl: string, params: CreateTeam$Params, context?: HttpContext): Observable<StrictHttpResponse<TeamDto>> {
  const rb = new RequestBuilder(rootUrl, createTeam.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TeamDto>;
    })
  );
}

createTeam.PATH = '/api/teams/{projectId}';
